"use strict";
/* ================= 스프라이트 빌더 ================= */
function makeSprite(rows, pal){
  const h = rows.length, w = rows[0].length;
  const c = document.createElement('canvas'); c.width = w; c.height = h;
  const g = c.getContext('2d');
  for(let y=0;y<h;y++)for(let x=0;x<rows[y].length;x++){
    const ch = rows[y][x];
    if(ch === '.' || !pal[ch]) continue;
    g.fillStyle = pal[ch]; g.fillRect(x,y,1,1);
  }
  return c;
}
function flipH(src){
  const c = document.createElement('canvas'); c.width=src.width; c.height=src.height;
  const g = c.getContext('2d'); g.translate(src.width,0); g.scale(-1,1); g.drawImage(src,0,0);
  return c;
}

/* ================= 사람 스프라이트 (팔레트 스왑) ================= */
const PERSON_DOWN = [
"....rrrrrrrr....",
"...rrrrrrrrrr...",
"..rrwwwwwwwwrr..",
"..kkkkkkkkkkkk..",
"..kssssssssssk..",
"..ksksskksksk...",
"..kssssssssssk..",
"...kssskkssss...",
"....ssssssss....",
"...bbbbbbbbbb...",
"..sbbbbbbbbbbs..",
"..sbbddddddbbs..",
"...bbbbbbbbbb...",
"....dd....dd....",
"....kk....kk....",
"...kkk....kkk...",
];
const PERSON_UP = [
"....rrrrrrrr....",
"...rrrrrrrrrr...",
"..rrrrrrrrrrrr..",
"..kkhhhhhhhhkk..",
"..khhhhhhhhhhk..",
"..khhhhhhhhhhk..",
"..khhhhhhhhhhk..",
"...hhhhhhhhhh...",
"....ssssssss....",
"...bbbbbbbbbb...",
"..sbbbbbbbbbbs..",
"..sbbddddddbbs..",
"...bbbbbbbbbb...",
"....dd....dd....",
"....kk....kk....",
"...kkk....kkk...",
];
const PERSON_LEFT = [
"....rrrrrrrr....",
"...rrrrrrrrr....",
"..rrwwwwwwrrr...",
"..kkkkkkkkkkk...",
"..kssssssssshk..",
"..kskssksssshk..",
"..kssssssssshk..",
"...ksskksssss...",
"....ssssssss....",
"...bbbbbbbbbb...",
"..sbbbbbbbbbb...",
"..sbbddddddbb...",
"...bbbbbbbbbb...",
"....dd..dd......",
"....kk..kk......",
"...kkk..kkk.....",
];
function makePerson(over){
  const pal = Object.assign({k:'#222034',s:'#f7c59f',r:'#d23b3b',w:'#fff5e8',b:'#3b6bd2',d:'#27408f',h:'#5a3a22'}, over);
  const left = makeSprite(PERSON_LEFT, pal);
  return { down:makeSprite(PERSON_DOWN,pal), up:makeSprite(PERSON_UP,pal), left, right:flipH(left) };
}
const PEOPLE = {
  player:     makePerson({}),
  rival:      makePerson({r:'#8a4ad2', b:'#3a3a4a', d:'#26262f', h:'#7a3ac2'}),
  professor:  makePerson({r:'#cfd3d8', b:'#ece8de', d:'#b8b0a0', h:'#9a9aa2'}),
  collector:  makePerson({r:'#3a9a4a', b:'#9a7a3a', d:'#7a5c22', h:'#2a2a2a'}),
  fisher:     makePerson({r:'#1a3a8a', b:'#2a9a8a', d:'#1a7a6a', h:'#3a3a3a'}),
  leader:     makePerson({r:'#7a2a1a', b:'#caa84a', d:'#9a7c2a', h:'#1a1a1a'}),
  researcher: makePerson({r:'#d28a2a', b:'#8a5ad2', d:'#6a3aa2', h:'#4a3a2a'}),
};

/* ================= 몬스터 스프라이트 ================= */
const SPR = {};
SPR['볼티'] = makeSprite([
"..k..........k.",
".kyk........kyk",
".kyyk......kyyk",
".kyoyk....kyoyk",
"..kyyykkkkyyyk.",
"..kyyyyyyyyyyk.",
".kyyyyyyyyyyyyk",
".kykwkyyyykwkyk",
".kykkkyyyykkkyk",
".kyyryyyyyyryyk",
".kyyyykkkkyyyyk",
"..kyyyyyyyyyyk.",
"..kyyyyyyyyyk..",
"...kyykkkyyk.kk",
"...kyyk.kyykkyk",
"....kk...kkkk..",
],{y:'#ffd93b',o:'#e8a020',k:'#222034',w:'#ffffff',r:'#e85a5a'});
SPR['볼트론'] = makeSprite([
".kk..........kk.",
"kyyk........kyyk",
"kyoyk......kyoyk",
".kyyyk....kyyyk.",
".kyyyykkkkyyyyk.",
"..kyyyyyyyyyyk..",
".kyyyyyyyyyyyyk.",
".kykwkyyyykwkyk.",
".kyykkyyyykkyyk.",
".kyyyyyrryyyyyk.",
".kyyyyokoyyyyyk.",
".kyyyyykoyyyyyk.",
"..kyyyyyyyyyyk..",
"..kyykkkkkkyyk..",
"..kyyk....kyyk..",
"...kk......kk...",
],{y:'#ffd93b',o:'#e87a10',k:'#222034',w:'#ffffff',r:'#e85a5a'});
SPR['새싹몬'] = makeSprite([
".....pkkp.......",
"....pkllkp......",
"....kllllk......",
".....klllk......",
"......klk.......",
"...kkggggkk.....",
"..kgggggggggk...",
".kgggggggggggk..",
".kgkwkgggkwkgk..",
".kgkkkgggkkkgk..",
".kgggggkgggggk..",
".kggggkkkggggk..",
"..kgggggggggk...",
"...kggggggggk...",
"....kgk..kgk....",
"....kkk..kkk....",
],{g:'#4fae4f',k:'#222034',w:'#fff',l:'#8ee08e',p:'#e87ab0'});
SPR['꽃숲몬'] = makeSprite([
"...pp.kk.pp.....",
"..pccpkkpccp....",
"..pccclllcccp...",
"...ppklllkpp....",
"....cklllkc.....",
"...kkgggggkk....",
"..kgggggggggk...",
".kgggggggggggk..",
".kgkwkgggkwkgk..",
".kgkkkgggkkkgk..",
".kggggkkkggggk..",
".kgggggggggggk..",
".klgggggggglgk..",
"..kggggggggggk..",
"...kggk..kggk...",
"...kkkk..kkkk...",
],{g:'#3f9a3f',k:'#222034',w:'#fff',l:'#8ee08e',p:'#e87ab0',c:'#ffd93b'});
SPR['불꼬리'] = makeSprite([
"............y...",
"...........yoy..",
"..kk......yooy..",
".krrk....koooy..",
".krrrk..krrok...",
"..krrrkkrrrk....",
"..krrrrrrrrk....",
".krrkwkrrkwkk...",
".krrkkkrrkkkk...",
".krrrrrrrrrrk...",
".korrrkkrrrok...",
".koorrrrrrook...",
"..koooooook.....",
"...koooook......",
"....kok.kok.....",
"....kk...kk.....",
],{r:'#e8602c',o:'#ffa53b',y:'#ffe06b',k:'#222034',w:'#fff'});
SPR['화염꼬리'] = makeSprite([
".kk....yy....kk.",
"krrk..yooy..krrk",
"krrrk.yooy.krrrk",
".krrrkkookrrrk..",
".krrrrrrrrrrrk..",
"..krrrrrrrrrk...",
".krrkwkrrkwkrk..",
".krrkkkrrkkkrk..",
".krrrrrrrrrrrky.",
".korrrkkkrrokyoy",
".koorrrrrrookyoy",
"..koooooooook.y.",
"..koooooooook...",
"...kooook.ook...",
"....kok...kok...",
"....kk.....kk...",
],{r:'#e8602c',o:'#ffa53b',y:'#ffe06b',k:'#222034',w:'#fff'});
SPR['물찌'] = makeSprite([
"......kkkk......",
"....kkbbbbkk....",
"...kbbbbbbbbk...",
"..kbblbbbblbbk..",
".kbbbbbbbbbbbbk.",
".kbkwkbbbbkwkbk.",
".kbkkkbbbbkkkbk.",
".kbbbbbbbbbbbbk.",
".kbbbkbbbbkbbbk.",
".kbbbbkkkkbbbbk.",
"..kbbbbbbbbbbk..",
"..kdbbbbbbbbdk..",
"...kddbbbbddk...",
"..kdkkddddkkdk..",
".kddk.kkkk.kddk.",
".kkk........kkk.",
],{b:'#4a90e8',d:'#2c5aa8',k:'#222034',w:'#fff',l:'#9bd0ff'});
SPR['물결몬'] = makeSprite([
"....kkkk........",
"...kbbbbk.......",
"..kblbwkbk......",
"..kbbbkkbk......",
"..kbbbbbbkkkk...",
"...kbbbbknnnnk..",
"..kkbbbknnddnnk.",
".kbbkbbknddddnk.",
".kbbbbbknnddnnk.",
"..kkbbbbknnnnk..",
"...kbbbbbkkkk...",
"...kbbbbbbbbk...",
"..kdbbbbbbbdk...",
"..kdkkbbbbkkdk..",
".kddk.kkkk.kddk.",
".kkk........kkk.",
],{b:'#4a90e8',d:'#2c5aa8',k:'#222034',w:'#fff',l:'#9bd0ff',n:'#b08850'});
SPR['돌돌이'] = makeSprite([
"....kkkkkkkk....",
"...kssssssssk...",
"..kssddssddssk..",
".kssssssssssssk.",
".ksdkwkssdkwksk.",
".ksdkkkssdkkksk.",
".kssssssssssssk.",
".kssskssssksssk.",
".ksssskkkkssssk.",
"kssksssssssksks.",
"ksskssddssksssk.",
".kssssssssssssk.",
".kdssddssddssdk.",
"..kdsssssssdk...",
"...kddddddddk...",
"....kkkkkkkk....",
],{s:'#a89888',d:'#7a6a58',k:'#222034',w:'#fff'});
SPR['바위왕'] = makeSprite([
"...kkkkkkkkkk...",
"..kssssssssssk..",
".kssdkwkdkwkssk.",
".kssdkkkdkkkssk.",
".kssssskkssssk..",
"kkssssskkssssskk",
"kssksssssssskssk",
"ksskssddddsskssk",
"ksskssssssssksgk" ,
"kggkssddddsskggk",
".kkssssssssssgk.",
".kdssddssddssdk.",
".kdsssssssssdk..",
"..kdddkkkdddk...",
".kddk.....kddk..",
".kkk.......kkk..",
],{s:'#a89888',d:'#7a6a58',k:'#222034',w:'#fff',g:'#8a7a68'});
SPR['파닥이'] = makeSprite([
"......kkkk......",
".....kbbbbk.....",
"....kbbwkbbk....",
"....kbbkkbbk....",
".....kbbbbyk....",
"..kk..kbbykk....",
".kbbk.kbbbk.....",
"kbbbbkbbbbbk.kk.",
"kbblbbbbblbbkbbk",
".kbbbbbbbbbbbbk.",
".kblbbbbbblbbk..",
"..kbbbbbbbbbk...",
"...kblbbblbk....",
"....kbbbbbk.....",
".....kyyk.......",
".....kyk........",
],{b:'#c0855a',l:'#e8c49b',k:'#222034',w:'#fff',y:'#ffd93b'});
SPR['폭풍새'] = makeSprite([
"k......kkk.....k",
"kbk...kbbbk..kbk",
"kbbk.kbwkbbk.kbk",
"kbbbkkbkkbbkkbbk",
"kblbbkbbbykbblbk",
".kbbbkbbyykbbbk.",
".kblbbkbbkbblbk.",
"..kbbbbbbbbbbk..",
"..kblbbbbbblbk..",
"...kbbbbbbbbk...",
"...kblbbbblbk...",
"....kbbbbbbk....",
".....klbblk.....",
"......kbbk......",
".....kyyyyk.....",
".....ky..yk.....",
],{b:'#9a6a4a',l:'#e8c49b',k:'#222034',w:'#fff',y:'#ffd93b'});

/* ================= 기술 / 타입 ================= */
const MOVES = {
  '몸통박치기':{type:'NOR',power:35},
  '할퀴기':{type:'NOR',power:40},
  '베어가르기':{type:'NOR',power:65},
  '전광석화':{type:'NOR',power:45},
  '전기쇼크':{type:'ELE',power:40},
  '번개':{type:'ELE',power:75},
  '번개폭풍':{type:'ELE',power:85},
  '덩굴채찍':{type:'GRS',power:40},
  '잎날가르기':{type:'GRS',power:50},
  '꽃잎댄스':{type:'GRS',power:80},
  '불꽃세례':{type:'FIR',power:45},
  '화염방사':{type:'FIR',power:70},
  '화염폭풍':{type:'FIR',power:85},
  '거품':{type:'WAT',power:35},
  '물대포':{type:'WAT',power:45},
  '하이드로펌프':{type:'WAT',power:85},
  '돌던지기':{type:'ROC',power:50},
  '암석포':{type:'ROC',power:80},
  '날개치기':{type:'FLY',power:40},
  '쪼기':{type:'FLY',power:45},
  '폭풍':{type:'FLY',power:80},
};
const TYPE_KO = {ELE:'전기',GRS:'풀',FIR:'불꽃',WAT:'물',ROC:'바위',FLY:'비행',NOR:'노말'};
const CHART = {
  ELE:{WAT:2,FLY:2,GRS:.5,ROC:.5},
  FIR:{GRS:2,WAT:.5,ROC:.5},
  WAT:{FIR:2,ROC:2,GRS:.5},
  GRS:{WAT:2,ROC:2,FIR:.5,FLY:.5},
  FLY:{GRS:2,ROC:.5},
  ROC:{FIR:2,FLY:2},
  NOR:{},
};

/* ================= 도감 ================= */
const DEX = {
  '볼티':  {no:1, type:'ELE',hp:35,atk:55,def:40,spd:90, exp:64, catch:.2, evolve:{lv:12,to:'볼트론'},
            desc:'볼을 비비면 정전기가 튄다. 사람을 잘 따른다.',
            learn:[[1,'몸통박치기'],[1,'전기쇼크'],[7,'전광석화'],[11,'번개']]},
  '볼트론':{no:2, type:'ELE',hp:60,atk:85,def:60,spd:110,exp:130,catch:.1,
            desc:'꼬리에 모은 전기로 번개 구름을 부른다.',
            learn:[[1,'몸통박치기'],[1,'전기쇼크'],[1,'전광석화'],[1,'번개'],[16,'번개폭풍']]},
  '새싹몬':{no:3, type:'GRS',hp:45,atk:49,def:49,spd:45, exp:55, catch:.55, evolve:{lv:13,to:'꽃숲몬'},
            desc:'머리의 새싹은 기분이 좋으면 살랑살랑 흔들린다.',
            learn:[[1,'몸통박치기'],[1,'덩굴채찍'],[8,'잎날가르기']]},
  '꽃숲몬':{no:4, type:'GRS',hp:65,atk:75,def:70,spd:55, exp:125,catch:.2,
            desc:'머리의 꽃에서 나는 달콤한 향기로 적을 잠재운다.',
            learn:[[1,'몸통박치기'],[1,'덩굴채찍'],[1,'잎날가르기'],[16,'꽃잎댄스']]},
  '불꼬리':{no:5, type:'FIR',hp:39,atk:52,def:43,spd:65, exp:60, catch:.35, evolve:{lv:13,to:'화염꼬리'},
            desc:'기분이 격해지면 꼬리의 불꽃이 두 배로 커진다.',
            learn:[[1,'할퀴기'],[1,'불꽃세례'],[10,'화염방사']]},
  '화염꼬리':{no:6,type:'FIR',hp:58,atk:80,def:58,spd:95, exp:128,catch:.15,
            desc:'두 갈래 불꼬리를 휘둘러 회오리 불길을 만든다.',
            learn:[[1,'할퀴기'],[1,'불꽃세례'],[1,'화염방사'],[16,'화염폭풍']]},
  '물찌':  {no:7, type:'WAT',hp:44,atk:48,def:50,spd:43, exp:58, catch:.5, evolve:{lv:13,to:'물결몬'},
            desc:'몸의 70%가 물. 마르면 기운이 없어진다.',
            learn:[[1,'몸통박치기'],[1,'거품'],[8,'물대포']]},
  '물결몬':{no:8, type:'WAT',hp:70,atk:70,def:80,spd:58, exp:126,catch:.18,
            desc:'등껍질에 물을 저장해 사막도 건널 수 있다.',
            learn:[[1,'몸통박치기'],[1,'거품'],[1,'물대포'],[16,'하이드로펌프']]},
  '돌돌이':{no:9, type:'ROC',hp:50,atk:55,def:70,spd:30, exp:60, catch:.45, evolve:{lv:14,to:'바위왕'},
            desc:'산길에서 자주 굴러 내려온다. 단단함이 자랑.',
            learn:[[1,'몸통박치기'],[1,'돌던지기'],[14,'베어가르기']]},
  '바위왕':{no:10,type:'ROC',hp:80,atk:85,def:110,spd:35,exp:135,catch:.1,
            desc:'산사태를 맨몸으로 막아낸 기록이 있다.',
            learn:[[1,'몸통박치기'],[1,'돌던지기'],[1,'베어가르기'],[17,'암석포']]},
  '파닥이':{no:11,type:'FLY',hp:40,atk:45,def:40,spd:70, exp:50, catch:.6, evolve:{lv:13,to:'폭풍새'},
            desc:'모래를 차올려 눈을 공격하는 영리한 새.',
            learn:[[1,'할퀴기'],[1,'쪼기'],[9,'날개치기']]},
  '폭풍새':{no:12,type:'FLY',hp:65,atk:75,def:60,spd:100,exp:122,catch:.12,
            desc:'날갯짓 한 번으로 폭풍을 일으킨다고 전해진다.',
            learn:[[1,'쪼기'],[1,'날개치기'],[16,'폭풍']]},
};
const DEX_ORDER = Object.keys(DEX).sort((a,b)=>DEX[a].no-DEX[b].no);

/* ================= 아이템 ================= */
const ITEMS = {
  ball:    {name:'몬스터볼',  price:200, desc:'야생 몬스터를 잡는다'},
  potion:  {name:'물약',      price:300, desc:'HP를 20 회복'},
  spotion: {name:'고급 물약', price:700, desc:'HP를 60 회복'},
};

/* ================= 맵 ================= */
// T나무 .잔디 ,길 w풀숲 ~물 F꽃 R지붕 W벽 D문 S표지판 f울타리 :모래 P기둥
const MAPS = {
  town: {
    name:'옐로 마을', music:'field',
    rows:[
      "TTTTTTTTTTTTTTTT,,TTTTTT",
      "TTTTTTTTTTTTTTTT,,TTTTTT",
      "TT.F..........F.,,....TT",
      "TT..RRRR...RRRR.,,.F..TT",
      "TT..RRRR...RRRR.,,....TT",
      "TT..WWDW...WWDW.,,....TT",
      "TT....,......,..,,..F.TT",
      "TT....,......,..,,....TT",
      "TT,,,,,,,,,,,,,,,,,...TT",
      "TT....,....S....,..F..TT",
      "TT....,..RRRR...,.....TT",
      "TT.F..,..RRRR...,..F..TT",
      "TT....,..WWDW...,.....TT",
      "TT....,....,....,.....TT",
      "TT,,,,,,,,,,,,,,,,,...TT",
      "TT~~~..........F......TT",
      "TT~~~....f,,,,f.......TT",
      "TT~~~....f,FF,f.......TT",
      "TT.F.....f,,,,f...F...TT",
      "TTTTTTTTTTTTTTTTTTTTTTTT",
    ],
    exits:{'16,0':{map:'route',x:16,y:28,dir:'up'},'17,0':{map:'route',x:17,y:28,dir:'up'}},
    doors:{'6,5':'pc','13,5':'heal','11,12':'shop'},
    signs:{'11,9':'「옐로 마을」 — 모험이 시작되는 조용한 마을\n북쪽 ▶ 1번 도로 · 몬스터 스타디움'},
    npcs:[
      {id:'prof', x:5,y:6, person:'professor', dir:'down', special:'professor'},
      {id:'res',  x:12,y:13, person:'researcher', dir:'down',
       lines:['풀숲의 몬스터는 약하게 만든 뒤 몬스터볼을 던지면 잡기 쉽다네.',
              '잡은 몬스터가 6마리를 넘으면 연구소 보관함으로 보내지지.',
              '집 문 앞에서 Z를 누르면 포켓 몬스터가 회복된다는 것도 잊지 말게!']},
    ],
    trainers:[],
    encounters:null,
  },
  route: {
    name:'1번 도로', music:'field',
    rows:[
      "TTTTTTTT,,TTTTTTTTTTTTTT",
      "TTTTTTTT,,TTTTTTTTTTTTTT",
      "TTwwww..,,..wwwwww....TT",
      "TTwwww..,,..wwwwww.F..TT",
      "TTwwww..,,..wwwwww....TT",
      "TT......,,............TT",
      "TT.F....,,...TTTTT....TT",
      "TT......,,...TTTTT....TT",
      "TTwwww..,,...wwwww....TT",
      "TTwwww..,,...wwwww....TT",
      "TTwwww..,,...wwwww....TT",
      "TT......,,............TT",
      "TT..F...,,......F.....TT",
      "TT......,,,,,,,,,,....TT",
      "TT.wwww.........,,.F..TT",
      "TT.wwww.........,,....TT",
      "TT.wwww..TTT....,,....TT",
      "TT.......TTT....,,....TT",
      "TT..wwww........,,....TT",
      "TT..wwww........,,....TT",
      "TT..wwww........,,....TT",
      "TT........F.....,,....TT",
      "TT....TTTT......,,....TT",
      "TT....TTTT......,,....TT",
      "TT..............,,.F..TT",
      "TT.F..wwwww.....,,....TT",
      "TT....wwwww.....,,....TT",
      "TT....wwwww.....,,....TT",
      "TT..............,,....TT",
      "TTTTTTTTTTTTTTTT,,TTTTTT",
    ],
    exits:{
      '8,0':{map:'stadium',x:8,y:14,dir:'up'},'9,0':{map:'stadium',x:9,y:14,dir:'up'},
      '16,29':{map:'town',x:16,y:1,dir:'down'},'17,29':{map:'town',x:17,y:1,dir:'down'},
    },
    doors:{}, signs:{},
    npcs:[],
    trainers:[
      {id:'t1', x:14,y:17, person:'collector', dir:'right', range:3,
       name:'수집가 민수', intro:'내 몬스터 컬렉션, 구경하고 갈래?',
       party:[['파닥이',5],['새싹몬',5]], prize:200,
       lose:'으악, 내 컬렉션이…!', after:'서쪽 풀숲엔 희귀한 몬스터도 나온대.'},
      {id:'rival1', x:10,y:8, person:'rival', dir:'left', range:2,
       name:'라이벌 라이라', intro:'어이, 노랑! 박사님께 몬스터 받았다며?\n누가 더 강한지 시험해 보자!',
       party:[['돌돌이',7]], prize:280,
       lose:'쳇! 바위가 전기에 강하다고 들었는데…', after:'스타디움에서 다시 붙자. 다음엔 안 져!'},
      {id:'t2', x:20,y:23, person:'fisher', dir:'left', range:4,
       name:'낚시꾼 동호', intro:'내 물찌들은 강물처럼 거세다구!',
       party:[['물찌',7],['물찌',6]], prize:280,
       lose:'물거품이 됐군…', after:'물 타입은 바위 타입에 강하지. 기억해 둬.'},
    ],
    encounters:{rate:.12, lvl:[3,6],
      pool:[['새싹몬',.25],['파닥이',.25],['물찌',.2],['불꼬리',.15],['돌돌이',.15]]},
  },
  stadium: {
    name:'몬스터 스타디움', music:'stadium',
    rows:[
      "TTTTTTTTTTTTTTTTTT",
      "T::::::::::::::::T",
      "T:P::::::::::::P:T",
      "T::::::::::::::::T",
      "T:P::::::::::::P:T",
      "T::::::::::::::::T",
      "T::::::::::::::::T",
      "T:P::::::::::::P:T",
      "T::::::::::::::::T",
      "T:P::::::::::::P:T",
      "T::::::::::::::::T",
      "T::::::::::::::::T",
      "T:P::::::::::::P:T",
      "T::::::::::::::::T",
      "T:::::::,,:::::::T",
      "TTTTTTTT,,TTTTTTTT",
    ],
    exits:{'8,15':{map:'route',x:8,y:1,dir:'down'},'9,15':{map:'route',x:9,y:1,dir:'down'}},
    doors:{}, signs:{},
    npcs:[],
    trainers:[
      {id:'rival2', x:11,y:13, person:'rival', dir:'left', range:3,
       name:'라이벌 라이라', intro:'역시 여기까지 왔구나!\n관장님과 붙기 전에 나부터 이겨 봐!',
       party:[['파닥이',10],['돌돌이',11]], prize:500,
       lose:'…강해졌네. 인정할게.', after:'관장님의 바위 타입은 물·풀 기술에 약해. …내가 왜 알려주는 거지?'},
      {id:'leader', x:9,y:3, person:'leader', dir:'down', range:10,
       name:'관장 강록', intro:'잘 왔다, 도전자여!\n나는 스타디움의 관장, 강록!\n바위의 단단함, 온몸으로 느껴 보아라!',
       party:[['돌돌이',12],['바위왕',15]], prize:1500, champion:true,
       lose:'완벽한… 패배다…', after:'너야말로 진정한 챔피언이다. 앞으로의 여정도 응원하마!'},
    ],
    encounters:null,
  },
};

/* ================= 음악 (미디 노트, 8분음표 스텝) ================= */
const SONGS = {
  title:{bpm:104, mel:[
    60,64,67,72, 76,72,67,64, 57,60,64,69, 72,69,64,60,
    58,62,65,70, 74,70,65,62, 59,62,67,71, 74,71,67,62],
    bass:[48,0,0,0, 43,0,0,0, 45,0,0,0, 41,0,0,0, 46,0,0,0, 41,0,0,0, 43,0,0,0, 43,0,0,0]},
  field:{bpm:120, mel:[
    72,0,71,72, 74,0,72,0, 71,0,69,71, 72,0,69,0,
    67,69,71,72, 74,76,74,72, 71,69,67,0, 64,0,67,0],
    bass:[48,0,55,0, 48,0,55,0, 45,0,52,0, 45,0,52,0, 41,0,48,0, 41,0,48,0, 43,0,50,0, 43,0,50,0]},
  battle:{bpm:152, mel:[
    69,0,69,71, 72,71,69,72, 71,0,67,0, 71,72,74,0,
    76,74,72,71, 69,71,72,69, 67,69,71,72, 71,69,67,0],
    bass:[45,45,0,45, 45,0,45,45, 41,41,0,41, 41,0,41,41, 43,43,0,43, 43,0,43,43, 40,40,0,40, 40,0,40,40]},
  victory:{bpm:132, once:true, mel:[
    67,67,67,67, 72,0,76,0, 74,72,74,76, 79,0,0,0],
    bass:[48,0,52,0, 55,0,52,0, 50,0,55,0, 48,0,0,0]},
  stadium:{bpm:138, mel:[
    57,0,60,64, 69,64,60,57, 55,0,59,62, 67,62,59,55,
    53,0,57,60, 65,60,57,53, 52,0,55,59, 64,59,57,52],
    bass:[45,45,0,45, 45,0,45,0, 43,43,0,43, 43,0,43,0,
          41,41,0,41, 41,0,41,0, 40,40,0,40, 40,0,40,0]},
};

const CREDITS = [
  '— 축하합니다! —','','스타디움 챔피언 등극!','',
  'POCKET MONSTERS Y','옐로 어드벤처','','기획 / 개발','Claude Code','',
  '그래픽','픽셀 아트 엔진','','음악','웹 오디오 칩튠','',
  '그리고','끝까지 함께한','파트너 볼티','','THE END','',
  '…모험은 계속된다!',
];
